### DISCUSSION TITLE
/bin/sh: 1: Syntax error: Unterminated quoted string - docker

### DISCUSSION THREAD

**Discussion by Supernova3339** [Retrospring/retrospring#1147] [Q&A]
Hi, whenever I attempt to deploy retrospring via docker, I get this message. This is from github directly, or the docker image.

**Comment by nilsding** [comment]
Hi, please tell us exactly what command you try to run, and what your setup looks like (container engine, etc.)

**Comment by Supernova3339** [comment]
Running on docker AMD based system.
That's really it.

**Comment by Supernova3339** [comment]
If it helps' it's ubuntu 22.04 server edition.

**Comment by nilsding** [comment]
Unfortunately, that doesn't help me at all.  How do you try to run it?

**Reply by Supernova3339** [reply]
I run it from the compose file

**Reply by nilsding** [reply]
That's a lot more helpful now.  We do not use docker-compose in our production deployments; this is only used for certain development setups.

pinging @pixeldesu, you know more about that stuff

**Reply by Supernova3339** [reply]
do you happen to know if there is a deployment guide for production?

**Reply by nilsding** [reply]
yes, there is none.  didn't find the time to write one yet ;-)

we essentially start our containers using `podman`, and manage the runtime of them through `systemd` (using its generated service units via `podman generate systemd`).  but these are details -- theoretically nothing stops you from letting something like kubernetes manage that for you.

starting a web container "by hand" is a matter of
```sh
# assuming overrides for 'config/justask.yml' and 'config/initializers/devise.rb' are in '/home/linux',
# postgresql is reachable at 'dbhost', and redis at 'redishost':
podman container run \
  --rm --replace -it \
  --name retrospring-web \
  -v /home/linux/justask.yml:/opt/retrospring/app/config/justask.yml \
  -v /home/linux/devise.rb:/opt/retrospring/app/config/initializers/devise.rb \
  -e SITE_NAME='not retrospring' \
  -e SECRET_KEY_BASE=hackme \
  -e 'DATABASE_URL=postgres://justask:hackme@dbhost/db_name?pool=25' \
  -e REDIS_URL=redis://redishost:6379 \
  -p 3000:3000 \
  ghcr.io/retrospring/retrospring:main \
  bundle exec puma -C config/puma.rb -b tcp://0.0.0.0:3000
```

note that setting up the postgresql database and redis is not done for you, this is something that needs to be done by yourself.

**Comment by pixeldesu** [comment]
We don't have documentation for the production Docker setup yet, since we don't use that ourselves even. The best bet for a quick startup is following parts of the [setup guide in the wiki](https://github.com/Retrospring/retrospring/wiki/Setup#setup-1) and looking at #1042 and the second command to run the container with the appropriate files mounted. (`podman` and `docker` can be used exactly the same). 

Might move the goal ahead to make the `docker-compose.yml` in the project to be a production-ready one.

----

In the meantime:

The compose file can also be adjusted to run the production image, should be something along the lines of this for the `web` service:

```yaml
  web:
    image: ghcr.io/retrospring/retrospring:main
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    environment:
      - SECRET_KEY_BASE=seeeecret
      - RAILS_LOG_TO_STDOUT=true
      - SPROCKETS_CACHE=/cache
      - DATABASE_URL=postgres://postgres:justask@postgres/justask_development?pool=25
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./config/database.yml:/opt/retrospring/app/config/database.yml
      - ./config/sidekiq.yml:/opt/retrospring/app/config/sidekiq.yml
      - ./config/justask.yml:/opt/retrospring/app/config/justask.yml
      - ./config/initializers/devise.rb:/opt/retrospring/app/config/initializers/devise.rb
      - ./:/app
      - cache:/cache
    ports:
      - 3000:3000
```

Things to adjust as well:
* don't forget to change the DB name in the `db` service and the `DATABASE_URL` environment in the `web` service.
* you also might want to set the `db` volume to be on the disk somewhere instead of a virtual one.
* probably also for the `redis` service, no idea what the path here is, but you do want to persist that, just in case.

_No guarantees this works, I wrote this up blindly on the fly right now_
